// Install and refresh the host-agent skill (SKILL.md) that teaches Claude Code,
// Cursor, and other agents how to drive the betterwright CLI.
//
// Content is always generated by the CLI (preamble + agentSystemPrompt), never
// copied from a stale vendored path for installs. There is intentionally no
// npm postinstall: that is forbidden by scripts/check-package.mjs and would
// surprise library consumers. Instead:
//   - `betterwright skill --install` writes known skill dirs (explicit)
//   - `refreshInstalledAgentSkills` rewrites only files that already exist
//     (called from setup / update)
//   - `staleAgentSkillReport` tips the operator on doctor when versions drift

import fs from "node:fs";
import { createRequire } from "node:module";
import os from "node:os";
import path from "node:path";

const require = createRequire(import.meta.url);

/** @typedef {"claude" | "agents" | "cursor"} SkillInstallTargetId */

/**
 * Conventional user skill destinations. Claude is the historical default;
 * `~/.agents/skills` is the open Agent Skills layout Cursor and others read.
 */
export const SKILL_INSTALL_TARGETS = [
  {
    id: "claude",
    label: "Claude Code",
    relativeDir: path.join(".claude", "skills", "browser"),
    defaultInstall: true,
  },
  {
    id: "agents",
    label: "Agent Skills",
    relativeDir: path.join(".agents", "skills", "browser"),
    defaultInstall: true,
  },
  {
    id: "cursor",
    label: "Cursor",
    relativeDir: path.join(".cursor", "skills", "browser"),
    defaultInstall: false,
  },
];

export function packageVersion() {
  try {
    return String(require("../../package.json").version || "");
  } catch {
    return "";
  }
}

/** YAML frontmatter for Claude-compatible SKILL.md, with a version stamp. */
export function claudeSkillFrontmatter(version = packageVersion()) {
  const ver = String(version || "").trim();
  const stamp = ver ? `\ngenerated_by: betterwright@${ver}` : "";
  return `---
name: browser
description: Drive a persistent, policy-guarded real web browser via the betterwright CLI. Use for any task that needs the live web — logging in, filling forms, booking, buying, or reading a page an API will not give you.${stamp}
---`;
}

/** Parse `generated_by: betterwright@X` from skill markdown (frontmatter). */
export function parseGeneratedBy(markdown) {
  const match = String(markdown || "").match(
    /^\s*generated_by:\s*betterwright@([^\s#]+)\s*$/m,
  );
  return match ? match[1] : null;
}

/**
 * @param {string} body skill body without frontmatter
 * @param {{version?: string}} [options]
 */
export function wrapClaudeSkillMarkdown(body, { version = packageVersion() } = {}) {
  return `${claudeSkillFrontmatter(version)}\n\n${String(body || "").trim()}\n`;
}

/**
 * @param {object} options
 * @param {string} [options.home]
 * @param {SkillInstallTargetId[]|"default"|"all"} [options.targets]
 */
export function resolveSkillInstallPaths({
  home = os.homedir(),
  targets = "default",
}: any = {}) {
  const ids =
    targets === "all"
      ? SKILL_INSTALL_TARGETS.map((t) => t.id)
      : targets === "default"
        ? SKILL_INSTALL_TARGETS.filter((t) => t.defaultInstall).map((t) => t.id)
        : [...targets];
  const wanted = new Set(ids);
  return SKILL_INSTALL_TARGETS.filter((t) => wanted.has(t.id)).map((t) => ({
    ...t,
    dir: path.join(home, t.relativeDir),
    file: path.join(home, t.relativeDir, "SKILL.md"),
  }));
}

/**
 * Write skill markdown to the chosen destinations.
 * @returns {{written: string[], skipped: string[]}}
 */
export function installAgentSkills({
  markdown,
  home = os.homedir(),
  targets = "default",
}: any = {}) {
  const content = String(markdown || "");
  if (!content.trim()) throw new Error("skill markdown is empty");
  const written = [];
  for (const dest of resolveSkillInstallPaths({ home, targets })) {
    fs.mkdirSync(dest.dir, { recursive: true });
    fs.writeFileSync(dest.file, content.endsWith("\n") ? content : `${content}\n`);
    written.push(dest.file);
  }
  return { written, skipped: [] };
}

/**
 * Rewrite managed skill files that already exist (safe after package upgrade).
 * Never creates new skill installs — that stays explicit via `skill --install`.
 * @returns {{refreshed: string[], missing: string[]}}
 */
export function refreshInstalledAgentSkills({
  markdown,
  home = os.homedir(),
  targets = "all",
}: any = {}) {
  const content = String(markdown || "");
  if (!content.trim()) throw new Error("skill markdown is empty");
  const refreshed = [];
  const missing = [];
  for (const dest of resolveSkillInstallPaths({ home, targets })) {
    if (!fs.existsSync(dest.file)) {
      missing.push(dest.file);
      continue;
    }
    // Only rewrite files that look like our managed skill (name: browser or
    // prior generated_by stamp / BetterWright heading). Avoid clobbering an
    // unrelated SKILL.md a user put in the same path.
    let existing = "";
    try {
      existing = fs.readFileSync(dest.file, "utf8");
    } catch {
      missing.push(dest.file);
      continue;
    }
    if (!isManagedBrowserSkill(existing)) {
      missing.push(dest.file);
      continue;
    }
    fs.writeFileSync(dest.file, content.endsWith("\n") ? content : `${content}\n`);
    refreshed.push(dest.file);
  }
  return { refreshed, missing };
}

export function isManagedBrowserSkill(markdown) {
  const text = String(markdown || "");
  if (/^\s*name:\s*browser\s*$/m.test(text)) return true;
  if (/generated_by:\s*betterwright@/i.test(text)) return true;
  if (/# Browser tool: BetterWright/i.test(text)) return true;
  return false;
}

/**
 * List installed managed skills whose generated_by does not match this package.
 * @returns {{file: string, installed: string|null, current: string}[]}
 */
export function staleAgentSkillReport({
  home = os.homedir(),
  version = packageVersion(),
  targets = "all",
} = {}) {
  const current = String(version || "").trim();
  const stale = [];
  for (const dest of resolveSkillInstallPaths({ home, targets })) {
    if (!fs.existsSync(dest.file)) continue;
    let existing = "";
    try {
      existing = fs.readFileSync(dest.file, "utf8");
    } catch {
      continue;
    }
    if (!isManagedBrowserSkill(existing)) continue;
    const installed = parseGeneratedBy(existing);
    if (!current) continue;
    if (installed !== current) {
      stale.push({ file: dest.file, installed, current });
    }
  }
  return stale;
}

/** One-line operator tip, or null when nothing is stale. */
export function staleAgentSkillTip(report = staleAgentSkillReport()) {
  if (!report.length) return null;
  const sample = report[0];
  const from = sample.installed ? `v${sample.installed}` : "unknown version";
  const n = report.length;
  return (
    `Agent skill is stale (${from} → v${sample.current}, ${n} file${n === 1 ? "" : "s"}). ` +
    "Run: betterwright skill --install"
  );
}
